language: ruby
rvm:
- 2.1
- 2.2
notifications:
  slack:
    secure: SLkfrjKn4L1J3sghg53QtvP9InoEvIgDpqsFBypxOH99EcI5XbonfBR/40Os66IFRzaLbGeSYY3/0ZEZiYnE7eEWr+q33uXomjGMSBSPdXKJ9GWFR1qou7vqu+K2TY6gzGK2VGpkp9YMRBrCDjxDgVilVAblH1N9Ba8DAAxggkaogm46UTkiy/37/uVSdvcqvLil6Stw/8jFR60ulJpC4hrIQzwqOQTWJNq6Czl3p4bWex+igNnQePZPg5/f/m6yG3KBptZZw2KryZNNMaEN8C6UDWf6l28oc2MFZecMTJvmBwjQlUzZcEy49/RHobSKhGG3V9yQ4fQoSrZjAT2wF4da4L7sCGGAyKFARySN2q0IRW2ES/c4VZTgB7ZW3HZvuJKbP65HQ+Sf775NtwOcepQ3dAr0dTOsHGEioDAeDdmMpx2eu5V+A3B/uz1mn07l5TfXC9V6mB176/gPBx/B9jnQWgKjCn4uquzxwTUBA+3LzZBl4vTN6c8slpJzbz2aPB36uy6HGqIV8KKxOyQ5zktBEXc2HxisE7QwV/Mq2HDsaqS98lzlbID/ClG4t7C66vZPIZmaXw8yvGQ2R9ic3Iv4u6BIAkBywZQdf/+V8yxLoeYbjYx83fsTUOwD5nnWP7PrVdeKXAF67fu11q7D5VmD60uHmuhCvOLqDyg4Ayk=
